meta:
  secrets: (( merge ))
  admin_secret: (( merge ))
  smoke_tests:
    org: (( merge || "smoke-tests" ))
    space: (( merge || "smoke-tests" ))
  instances: (( merge ))

jobs:
  - <<: (( merge ))
  - name: tests
    instances: (( meta.instances.tests ))

properties:
  domain: (( merge ))
  smoke_tests:
    api:  (( "api." properties.domain ))
    apps_domain: (( properties.domain ))
    user: admin
    password: (( meta.admin_secret ))
    skip_ssl_validation: true
    org: (( meta.smoke_tests.org ))
    space: (( meta.smoke_tests.org ))
    nodes: 1
