meta:
  networks:
    z1:
      apps: cf1

  data_templates:
  - name: debian-nfs-server-consul
    release: cf-consul
  - name: postgres-consul
    release: cf-consul
  - name: nats-consul
    release: cf-consul
  - name: nats-stream-forwarder-consul
    release: cf-consul
  - name: etcd-consul
    release: cf-consul
  - name: etcd-metrics-server-consul
    release: cf-consul
  - name: doppler-consul
    release: cf-consul
  - name: consul
    release: consul
  - name: vm-consul
    release: consul

  ha_proxy_templates:
  - name: haproxy-consul
    release: cf-consul
  - name: consul
    release: consul
  - name: vm-consul
    release: consul

  api_templates:
  - name: gorouter-consul
    release: cf-consul
  - name: cloud-controller-ng-consul
    release: cf-consul
  - name: nfs-mounter-consul
    release: cf-consul
  - name: consul
    release: consul
  - name: vm-consul
    release: consul

  services_templates:
  - name: uaa-consul
    release: cf-consul
  - name: login-consul
    release: cf-consul
  - name: cloud-controller-worker-consul
    release: cf-consul
  - name: etcd-consul
    release: cf-consul
  - name: nfs-mounter-consul
    release: cf-consul
  - name: consul
    release: consul
  - name: vm-consul
    release: consul

  dea_templates:
  - name: dea-next-consul
    release: cf-consul
  - name: dea-logging-agent-consul
    release: cf-consul
  - name: consul
    release: consul
  - name: vm-consul
    release: consul

  health_templates:
  - name: loggregator-trafficcontroller-consul
    release: cf-consul
  - name: hm9000-consul
    release: cf-consul
  - name: cloud-controller-clock-consul
    release: cf-consul
  - name: consul
    release: consul
  - name: vm-consul
    release: consul
jobs:
  - name: data
    properties:
      network: (( meta.networks.z1.apps ))

  - name: haproxy
    properties:
      network: lb1

  - name: api
    properties:
      network: (( meta.networks.z1.apps ))

  - name: services
    properties:
      network: (( meta.networks.z1.apps ))

  - name: health
    properties:
      network: (( meta.networks.z1.apps ))

  - name: runner_z1
    properties:
      network: (( meta.networks.z1.apps ))
