networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: manual
    subnets:
      - name: private
        range: 10.0.0.0/24
        gateway: 10.0.0.254
        reserved:
          - 10.0.0.1 - 10.0.0.10
        static:
          - 10.0.0.50 - 10.0.0.100
        cloud_properties:
          net_id: 1202c961-504d-4afb-b044-623787746307

jobs:
- instances: 1
  name: job1
  networks:
  - name: default
    static_ips:
    - 10.0.0.50
- instances: 1
  name: job2
  networks:
  - name: default
    static_ips:
    - 10.0.0.51
