meta:
  instances:
    api_worker_z1: (( merge || 1 ))
    etcd_z1: (( merge || 1 ))
    router_z1: (( merge || 1 ))
jobs:
  - name: api_worker_z1
    instances: (( meta.instances.api_worker_z1 ))
  - name: etcd_z1
    instances: (( meta.instances.etcd_z1 ))
  - name: router_z1
    instances: (( meta.instances.router_z1 ))
