meta:
  zones:
    z1: (( properties.template_only.aws.availability_zone ))
    z2: (( properties.template_only.aws.availability_zone2 ))
  instances: (( merge ))

resource_pools:
  - name: runner_z1
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( meta.zones.z1 ))

  - name: runner_z2
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( meta.zones.z2 ))

jobs:
  - name: runner_z1
    instances: (( meta.instances.runner_z1 ))

  - name: runner_z2
    instances: (( meta.instances.runner_z2 ))

properties:
  template_only: (( merge ))
