meta:
  secrets: (( merge ))
  admin_secret: (( merge ))
  smoke_tests:
    org: (( merge || "smoke-tests" ))
    space: (( merge || "smoke-tests" ))
  networks:
    z1:
      apps: cf1
    z2:
      apps: cf2

jobs:
  - name: acceptance_tests_runner
    instances: 1

  - name: smoke_tests_runner
    instances: 1

properties:
  domain: (( merge ))
  acceptance_tests:
    api:  (( "api." properties.domain ))
    apps_domain: (( properties.domain ))
    admin_user: admin
    admin_password: (( meta.admin_secret ))
    skip_ssl_validation: true
    nodes: 1

  smoke_tests:
    api:  (( "api." properties.domain ))
    apps_domain: (( properties.domain ))
    user: admin
    password: (( meta.admin_secret ))
    org: (( meta.smoke_tests.org ))
    space: (( meta.smoke_tests.org ))
    skip_ssl_validation: true
