meta:
  secrets: (( merge ))
  smoke_tests:
    org: (( merge || "smoke-tests" ))
    space: (( merge || "smoke-tests" ))

jobs:
  - <<: (( merge ))
  - name: tests
    instances: 1

properties:
  domain: (( merge ))
  smoke_tests:
    api:  (( "api." properties.domain ))
    apps_domain: (( properties.domain ))
    admin_user: admin
    admin_password: "c1oudc0w"
    user: admin
    password: "c1oudc0w"
    skip_ssl_validation: true
    org: (( meta.smoke_tests.org ))
    space: (( meta.smoke_tests.org ))
    nodes: 1
