networks: (( merge ))

properties:
  ccdb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - tag: cc
      name: ccdb
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: (( merge ))
      tag: admin

  uaadb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: (( merge ))
      tag: admin

  databases:
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: (( merge ))
      - tag: admin
        name: uaaadmin
        password: (( merge ))

    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

jobs:
  - name: postgres_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(4) ))