meta:
  floating_static_ips: (( merge ))
  ha_proxy:
    ssl_pem: (( merge || defaults.ha_proxy.ssl_pem ))

properties:
  domain: (( jobs.ha_proxy_z1.networks.floating.static_ips.[0] ".xip.io" ))

networks:
  - <<: (( merge ))
  - name: cf_lb1
    type: manual
    subnets:
      - range: IPMASK.2.0/24
        name: default_unused
        reserved:
          - IPMASK.2.2 - IPMASK.2.5
        static:
          - IPMASK.2.10 - IPMASK.2.100
        gateway: IPMASK.2.1
        dns:
          - IPMASK.0.2
        cloud_properties:
          security_groups:
            - CF_SG
          subnet: LB_SUBNET
  - name: floating
    type: vip
    cloud_properties: {}
properties:
  login:
    # Certificate to import if the UAA is using self-signed certificates
    uaa_certificate: (( meta.ha_proxy.ssl_pem ))
jobs:
  - name: ha_proxy_z1
    instances: 1
    networks:
      - name: floating
        static_ips: (( meta.floating_static_ips ))
      - name: cf_lb1
        static_ips: (( static_ips(0) ))
        default: [dns, gateway]
    properties:
      ha_proxy:
        ssl_pem: (( defaults.ha_proxy.ssl_pem ))

resource_pools:
  - name: router_z1
    cloud_properties:
      elbs: ~

  - name: router_z2
    cloud_properties:
      elbs: ~

defaults:
  ha_proxy:
    ssl_pem: |
      -----BEGIN CERTIFICATE-----
      MIICLzCCAZgCCQCSoIG3LoeSMTANBgkqhkiG9w0BAQUFADBcMQswCQYDVQQGEwJV
      UzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xEDAOBgNVBAoT
      B1Bpdm90YWwxFjAUBgNVBAsTDUNsb3VkIEZvdW5kcnkwHhcNMTMxMDE3MjMxNzM5
      WhcNMTQxMDE3MjMxNzM5WjBcMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAU
      BgNVBAcTDVNhbiBGcmFuY2lzY28xEDAOBgNVBAoTB1Bpdm90YWwxFjAUBgNVBAsT
      DUNsb3VkIEZvdW5kcnkwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBANqyjJMH
      FDbJ4XM2vLRxz6i82Gd2Y2dnAKYgu67FgheHGQJSv38lvn8JrAOBXu2QJgP8sJa+
      XqUWUTMo9BWvhvedQLojtcpLdULc0FhlIXn8bThGlTQyrSg9QJobhQZGziFVrdQM
      UZy4X+s6A2Szb9iOg3TYibnnfnuvdZli83eRAgMBAAEwDQYJKoZIhvcNAQEFBQAD
      gYEAbFu65WT+czpiJqHhNz5AnGYA8kieVlV7KhcljLtsU4Sxut5Vq9uXFBE09KCg
      YkyZ9KfzXArTeRCfcbm5xq12I+1nf6q0QjT1y3P6ztax0rpyb0i+4GWvA+ruMhfx
      n4QM1MkiJVYBGKkXFZDd1zsdR3pY4vm1uiMY75IvJQfgb08=
      -----END CERTIFICATE-----
      -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQDasoyTBxQ2yeFzNry0cc+ovNhndmNnZwCmILuuxYIXhxkCUr9/
      Jb5/CawDgV7tkCYD/LCWvl6lFlEzKPQVr4b3nUC6I7XKS3VC3NBYZSF5/G04RpU0
      Mq0oPUCaG4UGRs4hVa3UDFGcuF/rOgNks2/YjoN02Im55357r3WZYvN3kQIDAQAB
      AoGAa88G81fTBCtDA1vhbIaKWuE1QNOgrxGcxUhvnPlqZxTHJFkMY66EmPV4oYW9
      +RhNVTvVBYq092boAnNW1/Xebvrk1SnBDkrLntnGPmExkatOkPTFFlNXfePu6qOJ
      ULwYg8rKRwpvLoQXxbzMDXApPBifBNWGHVneGuHLpwPEQgECQQD0IJOecEyorrCR
      6+wmJBS/IwqQO0Ooj7kZEg65MHi9exVe+XFvP0lW2NAUsDuBLz79hjslSqIJjRG8
      c6q36oqhAkEA5VVeEip+T4DV12I5A5maGexVMeC92K7EGU/H8YhltxVZ/RtNngdT
      3r19WeDbDF7R5CJy2f7AYullk3S6fkk28QJBALdEiW1k4rezRMyW7tYHOifvN2vl
      gbpWAt/GRZVSxSGB+B4vZq/cM8NlynftgQ5PGJucnGQ3bgN7irgNoTimc2ECQFMX
      QBMy5DroAhKcmu2r/IKB90gwFnjosVI+bsIbWkcgbE9hUhj8rK2aWE11Q8hSnpea
      x6QmQgxUZiIr+9n/qvECQQDiDIeSmo2mRYsaqr4CQ3Ak+EDjsm9XTpXHuqm+xgFO
      iDIeQCWd3/twqdDTR7FaDE7Q0i559u7A1yLumUn8caLF
      -----END RSA PRIVATE KEY-----
